/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: kmeierhofer (https://sketchfab.com/kmeierhofer)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-cat-80ac4ce6cf72498eaa1572d6ec042aba
title: low poly cat
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/cat.glb', draco('/draco-gltf/'))
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials['null']} geometry={nodes.mesh_0.geometry} />
      </group>
    </group>
  )
}
